[project]
name = "vcc"
version = "0.1.0"
description = "Environment for the VCC challenge (locally)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]

[tool.uv.workspace]
members = [
]
